###  Endividamento

O ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transformação da lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilização do método ```.transpose ``` para certificar de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, impressão no output da segunda linha do array, depois a segunda coluna.

iii. Calculo do endividamento total usando a váriavel endividamento_total :
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$


iv. Correção de um valor considerando que há um erro de digitação que precisa ser corrigido ou um erro nas informações do banco de dados: 3o indivíduo não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. 

In [15]:
#i

import numpy as np

dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
nd_financeiros = np.array(dados_financeiros)

print(nd_financeiros)

[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [19]:
#ii

nd_financeiros = np.array(dados_financeiros)
nd_financeiros = nd_financeiros.transpose()


print("Segunda linha do array (segundo indivíduo):", nd_financeiros[1])


print("Segunda coluna do array (dívida financeira):", nd_financeiros[:, 1])

Segunda linha do array (segundo indivíduo): [2500 2500 5500]
Segunda coluna do array (dívida financeira): [1000 2500 3000 5000]


In [22]:
#iii

endividamento_total = np.sum(nd_financeiros, axis=1)

print("Endividamento total de cada indivíduo:")
print(endividamento_total)

Endividamento total de cada indivíduo:
[16500 11500 37500]


In [21]:
#iv

dados_financeiros = [[3000, 2500, 1000, 10000],
                     [1000, 2500, 3000, 5000],
                     [6000, 5500, 10000, 16000]] 

nd_financeiros = np.array(dados_financeiros)


endividamento_total_corrigido = np.sum(nd_financeiros, axis=1)


print("Endividamento total corrigido de cada indivíduo:")
print(endividamento_total_corrigido)


Endividamento total corrigido de cada indivíduo:
[16500 11500 37500]
